const projects = [
  { number: "01", label: "ORGANIZATIONAL SYSTEM", title: "Contract intake, approval & e-signature workflow", client: "Black Women's Health Imperative", problem: "Contract requests moved across teams, budgets, leaders, and signature steps without one consistent path.", solution: "Designed a structured workflow connecting intake, conditional approvals, tracking, and e-signature across Monday.com, Zapier, and DocuSign.", outcome: "A clearer end-to-end process with defined ownership, approval thresholds, status visibility, and fewer manual handoffs.", tags: ["Monday.com", "Zapier", "DocuSign", "Process design"] },
  { number: "02", label: "ACCESS & GOVERNANCE", title: "Software access governance & lifecycle controls", client: "Black Women's Health Imperative", problem: "Application ownership, user access, subscription costs, and onboarding/offboarding responsibilities needed to be centralized.", solution: "Inventoried software, mapped users and departments, centralized secure access through Okta and 1Password, and designed access review and provisioning processes.", outcome: "A stronger foundation for secure access, cost review, audit evidence, and timely employee and contractor lifecycle management.", tags: ["Okta", "1Password", "Access reviews", "SOPs"] },
  { number: "03", label: "PROCUREMENT & IMPLEMENTATION", title: "Learning management system selection", client: "Black Women's Health Imperative", problem: "Multiple programs needed one learning platform that could support engagement, reporting, certificates, commerce, and in-person learning.", solution: "Gathered requirements, vetted vendors, compared functionality and cost with Finance, and presented the business case and recommendation to organizational leadership.", outcome: "Decision-makers received a structured, requirements-based path for selecting a platform aligned with program and financial needs.", tags: ["Requirements", "Vendor evaluation", "Business case", "Implementation planning"] },
  { number: "04", label: "DATA & PROGRAM OPERATIONS", title: "Program submissions and participant tracking system", client: "Black Women's Health Imperative", problem: "Student records, submissions, approvals, surveys, media permissions, and calendar activity required coordinated tracking.", solution: "Designed connected operational boards with structured IDs, approval statuses, calendar synchronization, and post-program survey tracking.", outcome: "Program teams gained a more reliable operating view from participant intake through submission review and follow-up.", tags: ["Database design", "Monday.com", "Workflow logic", "Reporting"] },
  { number: "05", label: "CRM AUTOMATION", title: "Donation check intake automation", client: "Black Women's Health Imperative", problem: "Donation check details and supporting images were being re-entered across systems.", solution: "Built an automated handoff that sends check images and processing notes into Salesforce for centralized follow-through.", outcome: "Reduced duplicate entry and created a cleaner bridge between operational intake and donor records.", tags: ["Salesforce", "Zapier", "Data handoff", "Process improvement"] },
  { number: "06", label: "BARTER BLACK · LEAD AUTOMATION", title: "Lead inquiry and booking workflow", client: "Law firm · Barter Black project", problem: "Prospective-client inquiries and appointment booking required manual coordination, creating avoidable follow-up work and an inconsistent path from lead to consultation.", solution: "Mapped the full lead and booking process, clarified each handoff, and automated the repeatable steps connecting inquiry, follow-up, and scheduling.", outcome: "Created a more efficient intake path that reduces manual coordination and helps leads move toward a booked conversation more consistently.", tags: ["Process mapping", "Lead workflow", "Booking automation", "Client intake"] },
  { number: "07", label: "BARTER BLACK · BUSINESS AUTOMATION", title: "Client journey and workflow efficiency", client: "Salted Branding · Barter Black project", clientUrl: "https://saltedbranding.com/", problem: "The business needed a clearer view of how work moved across its client-facing process and where repeatable steps could be made more efficient.", solution: "Mapped the end-to-end business flow, identified manual friction and automation opportunities, and designed a more streamlined process around the client journey.", outcome: "Provided a clearer operating structure and a practical path for reducing repetitive work through automation.", tags: ["Business process mapping", "Client journey", "Automation design", "Efficiency"] },
  { number: "08", label: "BARTER BLACK · OPERATIONS MAPPING", title: "End-to-end operational process map", client: "Eye In Me · Barter Black project", clientUrl: "https://eyeinme.com/", problem: "The organization’s operational activities needed to be captured in one connected view so the full process and its dependencies could be understood.", solution: "Documented the complete operational process, organizing the stages, responsibilities, handoffs, and connections into a structured process map.", outcome: "Created a shared visual foundation for evaluating operations, clarifying how work flows, and identifying future improvements.", tags: ["Process mapping", "Operations", "Workflow analysis", "Documentation"] },
];

const demos = [
  ["Consulting intake system", "Lead capture, application review, approval and rejection communications."],
  ["Bakery ordering platform", "Customer ordering, pricing, fulfillment status and pickup communications."],
  ["Real estate inquiry assistant", "Property discovery supported by an AI phone experience for common questions."],
  ["Volunteer onboarding workflow", "Signup, screening, placement, communication and participation tracking."],
];

const capabilities = [
  ["Diagnose", "Clarify the real bottleneck, stakeholders, risks, and desired outcome."],
  ["Design", "Map the process, database, roles, approvals, and exception paths."],
  ["Build", "Configure the system, automation, forms, communications, and integrations."],
  ["Operationalize", "Document the process, train users, establish controls, and improve it over time."],
];

export default function Home() {
  return <main>
    <nav className="nav shell" aria-label="Main navigation"><a className="brand" href="#top"><span>JA</span> Jalaya Allen</a><div className="navlinks"><a href="#work">Work</a><a href="#services">Services</a><a href="#community">Community</a><a href="#about">About</a><a className="navcta" href="#book">Start a project</a></div></nav>
    <section className="hero shell" id="top"><div className="eyebrow"><i /> SYSTEMS & AUTOMATION CONSULTANT</div><h1>I turn scattered work into <em>systems that run.</em></h1><p className="lede">I help growing organizations replace manual handoffs, disconnected tools, and unclear processes with thoughtful workflows, automations, databases, and operating standards.</p><div className="hero-actions"><a className="button primary" href="#work">Explore selected work</a><a className="button text" href="/Jalaya-Allen-Portfolio.pdf" download>Download PDF <span>↓</span></a><a className="button text" href="https://www.linkedin.com/in/jalaya-a-671371198" target="_blank" rel="noreferrer" aria-label="Visit Jalaya Allen's LinkedIn profile">LinkedIn <span aria-hidden="true">↗</span></a></div><div className="proofbar"><div><strong>10+</strong><span>Systems & workflows designed</span></div><div><strong>15+</strong><span>Business platforms supported</span></div><div><strong>End-to-end</strong><span>From requirements to rollout</span></div></div></section>
    <section className="marquee" aria-label="Specialties"><div>PROCESS DESIGN <b>✦</b> AUTOMATION <b>✦</b> DATABASES <b>✦</b> GOVERNANCE <b>✦</b> IMPLEMENTATION <b>✦</b> SOPs</div></section>
    <section className="section shell" id="work"><div className="section-head"><div><span className="kicker">SELECTED WORK</span><h2>Systems built around<br/>real operational needs.</h2></div><p>Confidential details are intentionally limited. Each case study focuses on the challenge, the system design, and the operational value.</p></div><div className="projects">{projects.map(project => <article className="project" key={project.number}><div className="project-top"><span className="number">{project.number}</span><span className="label">{project.label}</span>{"clientUrl" in project && project.clientUrl ? <a className="client" href={project.clientUrl} target="_blank" rel="noreferrer">{project.client} ↗</a> : <span className="client">{project.client}</span>}</div><h3>{project.title}</h3><div className="project-grid"><div><b>THE CHALLENGE</b><p>{project.problem}</p></div><div><b>THE SYSTEM</b><p>{project.solution}</p></div><div className="outcome"><b>THE VALUE</b><p>{project.outcome}</p></div></div><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></article>)}</div></section>
    <section className="dark section" id="services"><div className="shell"><div className="section-head light"><div><span className="kicker">HOW I WORK</span><h2>More than an automation.<br/>A working operating system.</h2></div><p>The tool is only one layer. I design the process, information structure, ownership, controls, and adoption around it.</p></div><div className="capabilities">{capabilities.map((item,i)=><div className="cap" key={item[0]}><span>0{i+1}</span><h3>{item[0]}</h3><p>{item[1]}</p></div>)}</div><div className="services-grid"><div><span>01</span><h3>Workflow & automation design</h3><p>Intake, approvals, notifications, status changes, handoffs, and follow-up.</p></div><div><span>02</span><h3>Operational databases & CRM</h3><p>Connected records, useful views, ownership, pipelines, and reporting foundations.</p></div><div><span>03</span><h3>Systems implementation</h3><p>Requirements, vendor evaluation, configuration, rollout, and adoption planning.</p></div><div><span>04</span><h3>Governance & documentation</h3><p>Access controls, lifecycle processes, SOPs, policies, evidence, and review cadence.</p></div></div></div></section>
    <section className="section shell demos"><div className="section-head"><div><span className="kicker">INTERACTIVE CONCEPTS</span><h2>Business systems you can experience.</h2></div><p>Self-initiated demonstrations show how the same design thinking can serve service businesses, local businesses, property teams, and nonprofits.</p></div><div className="demo-grid">{demos.map((d,i)=><article key={d[0]}><span>CONCEPT 0{i+1}</span><h3>{d[0]}</h3><p>{d[1]}</p><b>Process + data + automation</b></article>)}</div></section>
    <section className="community section" id="community"><div className="shell"><div className="section-head"><div><span className="kicker">IN THE COMMUNITY</span><h2>Showing automation<br/>in action.</h2></div><p>As founder of SimpliAutomated Solutions, I exhibited at the Hampton Roads Community Foundation&apos;s Black Philanthropy Month event, inviting attendees to explore live automation demonstrations and discuss their operational challenges.</p></div><div className="event-grid"><figure className="event-main"><img src="/hrcf-black-philanthropy-booth.jpg" alt="Attendees gathered around the SimpliAutomated Solutions booth"/><figcaption>Sharing practical automation ideas with event attendees</figcaption></figure><figure className="event-portrait"><img src="/hrcf-black-philanthropy-conversation.jpg" alt="Jalaya Allen speaking with an attendee at the Black Philanthropy Month event"/><figcaption>Connecting one-on-one with community members</figcaption></figure><figure className="event-demo"><img src="/hrcf-black-philanthropy-demo.jpg" alt="Jalaya Allen demonstrating a system at the SimpliAutomated Solutions exhibitor table"/><figcaption>Demonstrating a workflow at the exhibitor table</figcaption></figure></div><article className="meet-greet"><img src="/hrcf-malinda-williams-meet-greet.jpg" alt="Jalaya Allen with Malinda Williams at a Hampton Roads Community Foundation meet and greet"/><div><span className="kicker">EVENT HIGHLIGHT</span><h3>A memorable meet-and-greet.</h3><p>I also had the opportunity to meet actress and entrepreneur Malinda Williams during the event&apos;s meet-and-greet.</p></div></article></div></section>
    <section className="about section" id="about"><div className="shell about-grid"><div className="about-intro"><span className="kicker">ABOUT JALAYA</span><h2>An operations mind with a builder&apos;s instinct.</h2><figure className="portrait"><img src="/jalaya-allen-headshot.jpg" alt="Jalaya Allen smiling in a yellow blazer" /><figcaption>Jalaya Allen · Visionary Operator & Systems Builder</figcaption></figure></div><div className="about-copy"><p>My foundation in Information Technology and hands-on experience across organizational operations, consulting, program development, and technical support allow me to understand both the systems and the people who rely on them.</p><p>I do more than contribute to projects: I connect direction, people, processes, and technology to turn ideas into structured plans and coordinated action.</p><p>I am especially passionate about using technology and structured programs to expand opportunity for students, Black women, and underserved communities.</p><div className="experience"><div><b>Black Women&apos;s Health Imperative</b><span>Operations Analyst</span></div><div><b>SimpliAutomated Solutions</b><span>Founder</span></div><div><b>Campus Connex</b><span>Founder</span></div><div><b>Synergistic Strategic Solutions</b><span>Programs & Training Technology Assistant</span></div><div><b>Medtronic</b><span>Information Technology Intern</span></div><div><b>Norfolk State University</b><span>IT Support / Spartan Tech</span></div></div></div></div></section>
    <section className="tools shell"><span>PLATFORMS & METHODS</span><div>Monday.com · Zapier · Make · n8n · Airtable · Salesforce · DocuSign · Dubsado · MyCase · Power Automate · Google Workspace · Microsoft 365 · Okta · 1Password · Softr · Lucidchart · Microsoft Visio · Process Mapping · Requirements Gathering</div></section>
    <section className="contact" id="book"><div className="shell"><span className="kicker">READY WHEN YOU ARE</span><h2>Let&apos;s build the system behind your next stage of growth.</h2><p>Best-fit projects involve a real operational bottleneck, repeatable work, or disconnected information that needs a clearer structure.</p><a className="button primary invert" href="#calendar">Start a conversation</a><div className="booking" id="calendar"><div className="booking-head"><div><span>DISCOVERY CALL</span><h3>Choose a time that works for you.</h3></div><p>We&apos;ll use this conversation to understand your challenge, explore the project, and determine whether I&apos;m the right person to help.</p></div><iframe src="https://calendly.com/allenjalayabusiness/discovery-meeting?hide_gdpr_banner=1" title="Book a discovery meeting with Jalaya Allen through Calendly" loading="lazy" allow="fullscreen"/></div><div className="contact-links"><p className="booking-fallback">Having trouble viewing the calendar? <a href="https://calendly.com/allenjalayabusiness/discovery-meeting" target="_blank" rel="noreferrer">Open Calendly in a new tab.</a></p></div></div></section>
    <footer className="shell"><span>© 2026 Jalaya Allen</span><a href="https://www.linkedin.com/in/jalaya-a-671371198" target="_blank" rel="noreferrer">LinkedIn ↗</a><span>Systems · Automation · Operations</span></footer>
  </main>;
}
